name: relay_app
description: A Relay App
publish_to: 'none'
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
