// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAThdSAbXIRZrhzjtYObH-6wxwF3atwtnE',
    appId: '1:853961275760:web:20b4257317f34b702fb7b5',
    messagingSenderId: '853961275760',
    projectId: 'relay-app-597ec',
    authDomain: 'relay-app-597ec.firebaseapp.com',
    storageBucket: 'relay-app-597ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzEfZTWvRwHExvAjRocX1Ei8wq0edWfsk',
    appId: '1:853961275760:android:9972f1af207372a42fb7b5',
    messagingSenderId: '853961275760',
    projectId: 'relay-app-597ec',
    storageBucket: 'relay-app-597ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHFJ3jw-wo5pqyKp-2V8UGfqzIQR_BWWE',
    appId: '1:853961275760:ios:194bff1d9a38c6e92fb7b5',
    messagingSenderId: '853961275760',
    projectId: 'relay-app-597ec',
    storageBucket: 'relay-app-597ec.firebasestorage.app',
    iosBundleId: 'com.example.relayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHFJ3jw-wo5pqyKp-2V8UGfqzIQR_BWWE',
    appId: '1:853961275760:ios:194bff1d9a38c6e92fb7b5',
    messagingSenderId: '853961275760',
    projectId: 'relay-app-597ec',
    storageBucket: 'relay-app-597ec.firebasestorage.app',
    iosBundleId: 'com.example.relayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAThdSAbXIRZrhzjtYObH-6wxwF3atwtnE',
    appId: '1:853961275760:web:e3e455e8d860b4752fb7b5',
    messagingSenderId: '853961275760',
    projectId: 'relay-app-597ec',
    authDomain: 'relay-app-597ec.firebaseapp.com',
    storageBucket: 'relay-app-597ec.firebasestorage.app',
  );
}
